working_directory = "./Code"
import = ["dotfiles/alacritty/tokyonight_night.toml"]
[shell]
program = "/opt/homebrew/bin/zellij"
args = ["--config-dir", "dotfiles/zellij"]

[window]
padding={x=4,y=4}
startup_mode = "Maximized"

[font]
size=15
normal = { family = "Hack Nerd Font", style = "Regular" }

[terminal]
osc52="CopyPaste"
