disabledProviders: 
  - claude-plugins
modelRoles: 
  # smol: anthropic/claude-fable-5:high
  smol: openai-codex/gpt-5.5:high
  default: openai-codex/gpt-5.5:xhigh
  # slow: anthropic/claude-fable-5:max
  slow: openai-codex/gpt-5.5:xhigh
  # plan: anthropic/claude-fable-5:max
  plan: openai-codex/gpt-5.5:xhigh
  # commit: anthropic/claude-sonnet-5:high
  commit: openai-codex/gpt-5.5:high
  # thinking: anthropic/claude-fable-5:max
  thinking: openai-codex/gpt-5.5:xhigh
  # vision: anthropic/claude-fable-5:max
  vision: openai-codex/gpt-5.5:xhigh
  # designer: anthropic/claude-fable-5:max
  designer: openai-codex/gpt-5.5:xhigh
  # task: anthropic/claude-fable-5:max
  task: openai-codex/gpt-5.5:xhigh
  advisor: openai-codex/gpt-5.5:xhigh
cycleOrder: 
  - smol
  - default
  - slow
  - commit
  - thinking
steeringMode: all
followUpMode: one-at-a-time
interruptMode: immediate
statusLine: 
  sessionAccent: true
  showHookStatus: true
  preset: nerd
  separator: powerline
tui: 
  hyperlinks: "off"
  textSizing: true
display: 
  showTokenUsage: true
  shimmer: classic
showHardwareCursor: true
defaultThinkingLevel: xhigh
retry: 
  maxRetries: 3
autoResume: false
doubleEscapeAction: tree
treeFilterMode: all
compaction: 
  strategy: context-full
  handoffSaveToDisk: true
  enabled: true
memory: 
  backend: local
edit: 
  mode: hashline
readLineNumbers: true
lsp: 
  formatOnWrite: true
  diagnosticsOnEdit: true
todo: 
  eager: always
renderMermaid: 
  enabled: true
calc: 
  enabled: true
inspect_image: 
  enabled: true
checkpoint: 
  enabled: true
github: 
  enabled: true
async: 
  enabled: true
tools: 
  discoveryMode: mcp-only
  intentTracing: false
bash: 
  autoBackground: 
    enabled: true
mcp: 
  discoveryMode: true
  notifications: true
theme: 
  dark: dark-catppuccin
  light: light
symbolPreset: nerd
providers: 
  webSearch: auto
  image: auto
  kimiApiFormat: openai
commands: 
  enableOpencodeProject: false
  enableOpencodeUser: false
  enableClaudeProject: false
  enableClaudeUser: false
skills: 
  enableSkillCommands: true
  enableClaudeUser: false
  enableClaudeProject: false
  enableCodexUser: false
task: 
  isolation: 
    merge: patch
  showResolvedModelBadge: true
  eager: always
  enableLsp: true
browser: 
  headless: true
clearOnShrink: false
contextPromotion: 
  enabled: false
marketplace: 
  autoUpdate: auto
setupVersion: 1
dev: 
  autoqa: 
    consent: granted