disabledProviders: 
  - claude-plugins
modelRoles: 
  smol: openai-codex/gpt-5.5:low
  default: openai-codex/gpt-5.5:medium
  slow: openai-codex/gpt-5.4:xhigh
  plan: openai-codex/gpt-5.5:medium
  commit: openai-codex/gpt-5.3-codex-spark:xhigh
  thinking: openai-codex/gpt-5.5:xhigh
  vision: openai-codex/gpt-5.4:xhigh
  designer: openai-codex/gpt-5.5:xhigh
  task: openai-codex/gpt-5.5:low
cycleOrder: 
  - smol
  - default
  - slow
  - commit
  - thinking
lastChangelogVersion: 15.5.12
steeringMode: all
followUpMode: one-at-a-time
interruptMode: immediate
statusLine: 
  sessionAccent: true
  showHookStatus: true
  preset: nerd
  separator: powerline
tui: 
  hyperlinks: always
display: 
  showTokenUsage: true
  shimmer: classic
showHardwareCursor: true
defaultThinkingLevel: xhigh
serviceTier: none
retry: 
  maxRetries: 3
autoResume: false
doubleEscapeAction: tree
treeFilterMode: all
compaction: 
  strategy: context-full
  handoffSaveToDisk: true
  enabled: true
memory: 
  backend: local
edit: 
  mode: hashline
readLineNumbers: true
lsp: 
  formatOnWrite: true
  diagnosticsOnEdit: true
todo: 
  eager: true
renderMermaid: 
  enabled: true
calc: 
  enabled: true
inspect_image: 
  enabled: true
checkpoint: 
  enabled: true
github: 
  enabled: true
async: 
  enabled: true
tools: 
  discoveryMode: mcp-only
  intentTracing: false
bash: 
  autoBackground: 
    enabled: true
mcp: 
  discoveryMode: true
  notifications: true
theme: 
  dark: dark-catppuccin
  light: dark-catppuccin
symbolPreset: nerd
providers: 
  webSearch: auto
  image: auto
  kimiApiFormat: openai
commands: 
  enableOpencodeProject: false
  enableOpencodeUser: false
  enableClaudeProject: false
  enableClaudeUser: false
skills: 
  enableSkillCommands: true
  enableClaudeUser: false
  enableClaudeProject: false
  enableCodexUser: false
task: 
  isolation: 
    merge: patch
browser: 
  headless: true
clearOnShrink: false
contextPromotion: 
  enabled: true
marketplace: 
  autoUpdate: auto